### ISSUE TITLE
Support Null Safety

### ISSUE THREAD

**Issue by whatamelon** [crizant/flutter_conditional_rendering#1]
I want to know you have plan for support null safety for this library.

**Comment by crizant** [comment]
Hi, this library don't have any dependency other than flutter itself, is there any difference to migrate or not?
Or do we have issues when using it on flutter 2.x?

**Comment by crizant** [comment]
Never mind, 2.0.0 released.

**Comment by whatamelon** [comment]
Thx a lot! :D
