### ISSUE TITLE
Optional fallbackBuilder

### ISSUE THREAD

**Issue by natty-pluz** [crizant/flutter_conditional_rendering#4]
Sometimes in ConditionalSwitch, the fallbackBuilder is not needed. I know I can assign an empty container, but it would be nice if it was optional.

**Comment by Arthurmtro** [comment]
@crizant any news on this ? would be nice

**Comment by crizant** [comment]
I see, so that’s two people requesting this feature. I will implement it next week.

**Comment by Arthurmtro** [comment]
If you want, I can open a pull request ;)

**Comment by crizant** [comment]
> If you want, I can open a pull request ;)

btw if fallbackBuilder is not provided, do you think I should return a `Container()` or just `null`?

**Comment by Arthurmtro** [comment]
It should return null actually

**Comment by crizant** [comment]
> It should return null actually

Then the return type of Conditional.single() will be “Widget?”, what do you think 🤔

**Comment by Arthurmtro** [comment]
Oh, ok, I got your point,
It's not a good idea to have this `?`, let's return an empty container so it won't change the return type of this widget : D

**Comment by crizant** [comment]
Version 2.1.0 released.
